### ISSUE TITLE
Error on server start

### ISSUE THREAD

**Issue by Jay420blaze** [MarlonGrazek/BetterHarvesting#2]
**Describe the bug**
Plugin error on startup

**To Reproduce**
1. add plugin to 1.18 server
2. start server
3. see error in console

**Expected behavior**
for the plugin to be enabled and not throw an error

**Screenshots**
![image](https://user-images.githubusercontent.com/67833262/147945150-313583ec-2c5f-4723-a137-d39f4767243e.png)

**Comment by MarlonGrazek** [comment]
it should be fixed now :)
