### ISSUE TITLE
Fortune support

### ISSUE THREAD

**Issue by Jay420blaze** [MarlonGrazek/BetterHarvesting#6]
**Is your feature request related to a problem? Please describe.**
When i use a fortune hoe on crops and right click it doesnt take into account the fortune effect

**Describe the solution you'd like**
I would like fortune hoes to drop more crops when right clicked

**Describe alternatives you've considered**
Not many alternatives...

**Additional context**
Loving the plugin now its working :)

**Comment by MarlonGrazek** [comment]
Thank you :)
Fortune is already in planning and I will probably include it in the next update

**Comment by MarlonGrazek** [comment]
added with version 1.2
